//register
###
POST http://localhost:6969/user/
Content-Type: application/json

{
    "username":"luan 123",
    "password":"123"
}

//login
###
POST http://localhost:6969/user/login
Content-Type: application/json

{
    "username":"luan123",
    "password":"123"
}
//
//add post
###
POST http://localhost:6969/post/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRXhpc3QiOiI2Mzk5ODM0NmZlYmRhZDA5OTQ5NTc3MTkiLCJpYXQiOjE2NzIzODI3MjV9.6j56SXu1arhcW4BJb9BZ7Wz7unQ6lUHYiYVM7OdlB0w

{
    "title":"hom nay di net",
    "content":["Di net","img","img"]
}
//get all post
###
GET http://localhost:6969/post/

//
//add behavior
###
POST http://localhost:6969/behavior/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRXhpc3QiOiI2MzhkN2VlZTBhMmRlMjE5NzEwYWZlYzkiLCJpYXQiOjE2NzA5OTI0OTl9.ifog5ln6GYN0k1AbtEMCHlWIGpI7DEct3L-bwKqe19o

{
    "like":"Smile"
}
//
//get one behavior by post id
###
GET http://localhost:6969/behavior/639beef7ec3662744cd4bbb2


//update behavior by post id
###
PUT http://localhost:6969/behavior/63b58c5c975850508383e98e
Content-Type: application/json

{
    # "like":
    #    {
    #         "user":"63998346febdad0994957719",
    #         "likeContent":"smil zze"
    #    }
    # ,
    "comment":
       {
            "userid":"63998346febdad0994957719",
            "user":"yea",
            "CommentContent":"haha"

       }
    
   
}